# Generated by Django 2.2.6 on 2019-10-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ingredient',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
