# Generated by Django 2.2.6 on 2019-11-10 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_menu_ingredient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='ingredient',
            new_name='ingredient1',
        ),
    ]
