# Generated by Django 2.2.6 on 2019-11-11 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_auto_20191110_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ingredient2',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='ingredient3',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='ingredient4',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='ingredient5',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ingredient1',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
