# Generated by Django 2.2.6 on 2019-11-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0004_auto_20191111_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='ingredient6',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
