# Generated by Django 2.2.6 on 2019-11-11 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0005_menu_ingredient6'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='ingredient5',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
