# Generated by Django 2.2.6 on 2020-04-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0012_auto_20200415_1132'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Essential_ingredient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
