# Generated by Django 2.2.6 on 2020-04-15 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0013_auto_20200415_1137'),
    ]

    operations = [
        migrations.RenameField('Menu', 'Essential_ingredient', 'practice_ingredient')
    ]
