# Generated by Django 2.2.6 on 2020-04-15 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0014_auto_20200415_1138'),
    ]

    operations = [
            migrations.RenameField('Menu', 'practice_ingredient', 'Essential_Ingredient')
    ]
