# Generated by Django 2.2.6 on 2020-04-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0015_auto_20200415_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='Nonessential_Ingredient',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
