# Generated by Django 2.2.6 on 2020-04-15 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0016_menu_nonessential_ingredient'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='Essential_Ingredient',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='Nonessential_Ingredient',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='menu',
            name='link',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
