# Generated by Django 2.2.6 on 2020-04-15 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0017_auto_20200415_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='tip',
            field=models.TextField(blank=True, default=''),
        ),
    ]
