# Generated by Django 3.1 on 2020-08-22 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0018_menu_tip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name_plural': 'Menu'},
        ),
    ]
